l_spanish:
 SETTING_DEBUG_SAVES: "Número de saves de debug"
 SETTING_TUTORIAL: "Tutorial"
 SETTING_DISABLED_HINTS: "Dicas desativadas"
 #SETTING_FOCUS_ON_COMBAT: "" # <DELETE THIS KEY>
 SETTING_TOOLTIP_DELAY: "Atraso da dica"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nDefine o atraso antes de as dicas aparecerem."
 SETTING_TOOLTIP_UNLOCK_TIME: "Atraso para destravar"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nDefine o atraso antes de as dicas serem destravadas."
 SETTING_TOOLTIP_LOCK_TIME: "Atraso para travar"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nDefine o atraso antes de as dicas serem travadas."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Atraso de abertura travada"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nDefine o atraso antes de as dicas serem travadas quando outra dica já está aberta."
 #Audio
 SETTING_Sound_Effects: "Todos os efeitos sonoros"
 SETTING_Sound_Effects_TOOLTIP: "#T Volume dos efeitos sonoros\n#!Define o volume de TODOS os efeitos sonoros."
 SETTING_Ambience: "Ambiência"
 SETTING_Ambience_TOOLTIP: "#T Volume da ambiência\n#!Define o volume da ambiência do ambiente."
 SETTING_TOOLTIP_MODE: "Modo de dica"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nDefine a forma como as dicas ficam \"travadas\", permitindo dicas dentro de dicas."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Tendência do mouse"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nAs dicas travam automaticamente no lugar até que o cursor se afaste."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION: "Travamento por ação"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nPressione #V Botão do Meio do Mouse#! para travar e destravar dicas."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER: "Travamento por tempo"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP: "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nAs dicas ficam travadas no lugar se o cursor não se mover por um curto período. #weak (Configuração padrão.)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC: "Diversos"
 SETTINGS_CATEGORY_TOOLTIPS: "Dicas"
 SETTINGS_CATEGORY_SFX: "Efeitos sonoros específicos"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "Geral"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Controles do mapa"
 SETTINGS_CATEGORY_SAVE_GAMES: "Jogos salvos"
 SETTINGS_CATEGORY_LANGUAGE: "Idioma"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Avançado – Geral"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_MAP: "Avançado – Mapa"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_Characters: "Avançado – Personagens"
 SETTINGS_CATEGORY_GAME_PORTRAITS: "Retratos"
 SETTINGS_CATEGORY_GAME_EVENTS: "Eventos"
 SETTINGS_CATEGORY_GAME_FLAVOR: "Ambientação"
 SETTINGS_CATEGORY_MULTIPLAYER: "Multijogador"
 SETTINGS_CATEGORY_MAP: "Mapa"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS: "Mostrar doenças e ferimentos gráficos"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP: "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nDefine se ferimentos e doenças gráficas serão visíveis nos retratos dos personagens."
 SETTING_SHOW_NUDITY: "Mostrar nudez"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nDefine se personagens podem ser mostrados nus."
 SETTINGS_CATEGORY_GAME_DLC_MODS: "Conteúdo para download"
 SETTING_SHOW_CONTENT_SOURCE: "Mostrar DLC do evento"
 SETTING_SHOW_CONTENT_SOURCE_TOOLTIP: "#T $SETTING_SHOW_CONTENT_SOURCE$#!\nDefine se os eventos mostram de qual DLC vieram."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE: "Panorâmica ociosa da Corte Real"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE_TOOLTIP: "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE$#!\nDetermina se a câmera na Corte Real deve percorrer suavemente sua Corte quando estiver ociosa.\n\nSe Personagens Animados estiver desligado, esta configuração não terá efeito."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION: "Transições suaves da Corte Real"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION_TOOLTIP: "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION$#!\nDetermina se a câmera na Corte Real deve se mover suavemente para um novo local.\n\nSe Personagens Animados estiver desligado, esta configuração não terá efeito."
 NEVER: "Nunca"
 MONTHLY: "Todo mês"
 HALFYEAR: "A cada 6 meses"
 YEARLY: "Todo ano"
 FIVE_YEAR: "A cada 5 anos"
 SETTINGS_CATEGORY_TUTORIAL: "Tutorial"
 SETTING_REACTIVE_TUTORIAL: "Mostrar conselhos reativos"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP: "#T $SETTING_REACTIVE_TUTORIAL$#!\nDefine se o jogo deve mostrar conselhos de tutorial reagindo à forma como você joga. Útil para jogadores novos em Crusader Kings III."
 SETTING_SHOW_SUGGESTIONS: "Mostrar sugestões"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP: "#T $SETTING_SHOW_SUGGESTIONS$#!\nEstabelece se o jogo deve sugerir atividades em intervalos regulares. Útil para jogadores que estão descobrindo Crusader Kings III."
 RESET_REACTIVE_ADVICE: "Redefinir conselhos reativos"
 RESET_REACTIVE_ADVICE_TOOLTIP: "#T Redefinir conselhos reativos#!\nOs conselhos reativos vistos anteriormente voltarão a aparecer."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE: "Redefinir conselhos reativos"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT: "Tem certeza de que deseja redefinir os conselhos reativos?"
 SETTING_ADVANCED_SHADERS: "Efeitos avançados de shader"
 SETTING_ADVANCED_SHADERS_TOOLTIP: "#T Efeitos avançados de shader\n#!Esta opção habilitará efeitos avançados de shader.\n\nDesligá-la pode aumentar o desempenho, ao custo de fazer alguns efeitos (por ex.: terreno e água) parecerem piores"
 SETTING_WINTER_PARTICLE_EFFECTS: "Efeitos de partículas de inverno"
 SETTING_WINTER_PARTICLE_EFFECTS_TOOLTIP: "#T $SETTING_WINTER_PARTICLE_EFFECTS$#!\nDetermina se os efeitos de partículas serão exibidos ou não quando o inverno estiver ativo em algumas áreas do mapa.\n\nDesativá-los pode melhorar o desempenho."
 SETTING_RESET_CAMERA_ROTATION: "Redefinição da rotação da câmera"
 SETTING_RESET_CAMERA_ROTATION_TOOLTIP: "#T $SETTING_RESET_CAMERA_ROTATION$#!\nDetermina se a câmera deve voltar automaticamente à posição padrão após ser girada pelo usuário."
 SETTING_TILT_CAMERA_ON_ZOOM_OUT: "Inclinar câmera ao afastar zoom"
 SETTING_TILT_CAMERA_ON_ZOOM_OUT_TOOLTIP: "#T $SETTING_TILT_CAMERA_ON_ZOOM_OUT$#!\nControla se a câmera deve tender à inclinação padrão ao afastar a imagem."
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS: "Personagens de fundo da cena da corte"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS_TOOLTIP: "#T $SETTING_RESET_CAMERA_ROTATION$#!\nDetermina se a cena 3D da Corte Real deve exibir personagens de fundo menos importantes."
 SETTING_MAP_HIGHLIGHT: "Destaque do cursor no mapa"
 SETTING_MAP_HIGHLIGHT_TOOLTIP: "#T $SETTING_MAP_HIGHLIGHT$#!\nDetermina a intensidade dos destaques do cursor no mapa"
 SETTING_MAP_OVERLORD_HIGHLIGHT: "Destaque do senhor supremo no mapa"
 SETTING_MAP_OVERLORD_HIGHLIGHT_TOOLTIP: "#T $SETTING_MAP_OVERLORD_HIGHLIGHT$#!\nDetermina quando o suserano máximo de um reino é destacado ao selecionar um reino."
 OPTION_ALWAYS: "Sempre"
 OPTION_TRIBUTARY_ONLY: "Somente tributários"
 BASED_ON_ZOOM_LEVEL: "Dinâmico"
 ALWAYS_HIDE: "Sempre ocultar"
 ALWAYS_SHOW: "Sempre mostrar"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM: "Fronteiras costeiras"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP: "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nEsta opção determina se as fronteiras costeiras serão exibidas ou não.\nSe você escolher $BASED_ON_ZOOM_LEVEL$, elas serão ocultadas no nível de zoom de detalhe.\n\nSe você escolher $ALWAYS_SHOW$ ou $ALWAYS_HIDE$, isso pode melhorar o desempenho, mas as fronteiras costeiras do domínio não serão ocultadas dinamicamente."
 SETTINGS_DISCARD_CHANGES: "Descartar alterações"
 ONLY_TOOLTIPS: "Somente nas dicas"
 OPTIONS_AND_TOOLTIPS: "Em opções e dicas"
 NOWHERE: "Em lugar nenhum"
 SETTING_SHOW_EVENT_SHORTCUTS: "Mostrar atalhos das opções de evento"
 SETTING_SHOW_EVENT_SHORTCUTS_TOOLTIP: "#T $SETTING_SHOW_EVENT_SHORTCUTS$#!\nFija dónde mostrar atajos numéricos para las opciones de eventos.\nAtajos:\n#i Mayús+n.º para elegir una opción\nAlt+n.º para vista previa y confirmar una\nAlt+E para una vista previa de todas las opciones#!"
 SETTING_HUD_SKIN: "Tema do HUD"
 hud_skin_auto: "Dinâmico"
 default: "Padrão"
 iberian: "@fateofiberia_icon! Fate of Iberia"
 Norse: "@wrath_icon! Northern Lords"
 byzantine: "@roadstopower_icon! Roads to Power"
 iranian: "@legacyofpersia_icon! Legacy of Persia"
 nomad: "@khansofthesteppe_icon! Khans of the Steppe"
 asia: "@allunderheaven_icon! All Under Heaven"
 SETTING_HUD_SKIN_TOOLTIP: "#T $SETTING_HUD_SKIN$#!\nDefine o tema visual da interface HUD - a UI 2D mostrada na tela principal do jogo.\n\nSe $hud_skin_auto$ estiver selecionado, o HUD mudará de acordo com a cultura, fé e capital do reino do jogador."
 SETTING_RICH_PRESENCE: "Rich Presence"
 SETTING_RICH_PRESENCE_TOOLTIP: "#T $SETTING_RICH_PRESENCE$#!\nMostra informações sobre sua sessão atual de jogo aos seus amigos, se sua plataforma suportar isso."
 SETTING_USE_DYNASTY_NAMED_REALMS: "Reinos nomeados pela dinastia"
 SETTING_USE_DYNASTY_NAMED_REALMS_TOOLTIP: "#T $SETTING_USE_DYNASTY_NAMED_REALMS$#!\nAlgumas culturas denominam seu título principal a partir de sua dinastia (ex.: abasidas)."
 map_table_style_auto: "Dinâmico"
 map_table_style_western: "Padrão"
 map_table_style_ce1: "@legendsofthedead_icon! Legends of the Dead"
 map_table_style_ep3: "@roadstopower_icon! Roads to Power"
 map_table_style_tgp: "@allunderheaven_icon! All Under Heaven"
 SETTING_MAP_TABLE_STYLE: "Estilo da mesa do mapa"
 SETTING_MAP_TABLE_STYLE_TOOLTIP: "#T $SETTING_MAP_TABLE_STYLE$#!\nDefine o estilo visual da mesa do mapa - o mapa e o ambiente 3D mostrados ao afastar o zoom.\n\nSe $map_table_style_auto$ estiver selecionado, um estilo de mesa do mapa será escolhido com base no Jogador atual e em seu personagem."
 SETTING_SHOW_EVENT_NAME_PLATES: "Mostrar plaquetas de nome em eventos"
 SETTING_SHOW_EVENT_NAME_PLATES_TOOLTIP: "#T $SETTING_SHOW_EVENT_NAME_PLATES$#!\nMostra nomes, relações e opiniões dos personagens nos eventos.\nAlém disso, aparecerão dicas dos personagens sobre as plaquetas de nome em vez de retratos para facilitar a seleção.\nAplica-se apenas a eventos comuns, desativado para duelos e atividades."
 SETTINGS_CATEGORY_STYLING: "Estilo da interface"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS: "Gráficos de doenças"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS$#!\nControla se os efeitos das doenças aparecem no mapa"
 SETTING_SHOW_LEGEND_MAP_GRAPHICS: "Gráficos de lendas"
 SETTING_SHOW_LEGEND_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_LEGEND_MAP_GRAPHICS$#!\nControla se os efeitos das lendas aparecem no mapa"
 SETTING_SHOW_DETAILED_RAID_MAP_ICON: "Ícones detalhados de [raid|El]"
 SETTING_SHOW_DETAILED_RAID_MAP_ICON_TOOLTIP: "#T $SETTING_SHOW_DETAILED_RAID_MAP_ICON$#!\nMarca si los iconos de mapa de [raid|lE] muestran las versiones simplificadas o detalladas\n\n#I Si está activado, mantener Alt para mostrar todas las posesiones con botín que se pueden [Concept('raid', 'asaltar')|E].#!"
 SETTING_SHOW_DETAILED_BARTER_MAP_ICON: "Ícones de [Concept('barter', 'troca')|E] detalhados"
 SETTING_SHOW_DETAILED_BARTER_MAP_ICON_TOOLTIP: "#T $SETTING_SHOW_DETAILED_RAID_MAP_ICON$#!\nMarca si los iconos de mapa de [Concept('barter', 'trueque')|E] muestran las versiones simplificadas o detalladas\n\n#I Si está activado, mantener Alt para mostrar todas las posesiones con botín que se pueden [Concept('barter', 'trocar')|E].#!"
 SETTING_PAPER_MAP_STYLE: "Estilo do mapa de papel"
 SETTING_PAPER_MAP_STYLE_TOOLTIP: "#T $SETTING_PAPER_MAP_STYLE$#!\nDefine o estilo do mapa mostrado quando o mapa está com zoom afastado.\n\nSe $paper_map_style_auto$ estiver selecionado, o mapa de papel seguirá o estilo usado por \"$SETTING_MAP_TABLE_STYLE$\"\"."
 paper_map_style_auto: "Dinâmico"
 paper_map_style_western: "Padrão"
 paper_map_style_tgp: "All Under Heaven"
 SETTING_ADAPTIVE_FRAMERATE: "Taxa de quadros adaptativa"
 SETTING_ADAPTIVE_FRAMERATE_TOOLTIP: "#T $SETTING_ADAPTIVE_FRAMERATE$\n#!Reduz a taxa de atualização da tela se a velocidade de atualização do jogo cair, para melhorar o desempenho da jogabilidade."
 SETTING_HIDE_MAP_TABLE: "Ocultar mesa do mapa"
 SETTING_HIDE_MAP_TABLE_TOOLTIP: "#T $SETTING_HIDE_MAP_TABLE$\n#!Oculta a geometria da mesa do mapa."
 SETTING_HAS_CLOUD_SHADOW_ENABLED: "Sombra de nuvem"
 SETTING_HAS_CLOUD_SHADOW_ENABLED_TOOLTIP: "#T $SETTING_HAS_CLOUD_SHADOW_ENABLED$#!\nDefine se efeitos de sombra de nuvens devem ser mostrados no terreno"
 SETTING_HAS_TREE_DITHERING_ENABLED: "Dithering de árvores"
 SETTING_HAS_TREE_DITHERING_ENABLED_TOOLTIP: "#T $SETTING_HAS_TREE_DITHERING_ENABLED$#!\nDefine se efeitos de dithering devem ser aplicados às árvores para suavizar as bordas"
 SETTING_MAP_BRIGHTNESS: "Brilho do mapa de papel"
 SETTING_MAP_BRIGHTNESS_TOOLTIP: "#T $SETTING_MAP_HIGHLIGHT$#!\nDetermina a intensidade do brilho do mapa de papel"
