l_spanish:
 is_your_child_desc: "É Seu Filho"
 is_your_close_family_desc: "É da Sua Família Próxima"
 is_your_house_desc: "É da Sua Casa"
 landed_spouse_desc: "Tem Cônjuge com Terras"
 landed_heir_desc: "Tem Herdeiro com Terras"
 has_many_good_relations_desc: "Tem Muitos Amigos"
 has_many_bad_relations_desc: "É Cercado de Rivais"
 part_of_feud_desc: "Faz Parte de uma Rixa"
 high_diplomacy_desc: "Tem Alta Diplomacia"
 high_martial_desc: "Tem Alta Proficiência Marcial"
 high_stewardship_desc: "Tem Alta Administração"
 high_intrigue_desc: "Tem Alta Intriga"
 high_learning_desc: "Tem Alta Erudição"
 high_prowess_desc: "Tem Alta Proeza"
 high_education_desc: "É Altamente Educado"
 more_beautiful_desc: "É Mais Belo que o Herdeiro"
 more_smart_desc: "É Mais Inteligente que o Herdeiro"
 more_fit_desc: "É Mais Vigoroso que o Herdeiro"
 more_strong_desc: "É Mais Forte que o Herdeiro"
 more_skillful_desc: "É Mais Habilidoso que o Herdeiro"
 has_nickname_desc: "Tem um Apelido"
 more_famous_desc: "Mais Famoso que o Herdeiro"
 second_in_line_desc: "Segundo na Linha de Sucessão"
 higher_title_desc: "Possui um Título Superior"
 new_liege_desc: "Ficaria sob um Novo Suserano"
 new_top_liege_desc: "Ficaria sob um Novo Suserano Supremo"
 tall_claims_desc: "Possui Reivindicações Importantes"
 pressed_claims_desc: "Possui Reivindicações Pressionadas"
 unpressed_claims_desc: "Possui Reivindicações Não Pressionadas"
 inheritance_line_desc: "Na Linha de Sucessão"
 has_interesting_story_desc: "Tem uma História Interessante"
 child_of_destiny_desc: "É uma Criança do Destino"
 virtues_interesting_desc: "Tem Traços Virtuosos"
 tourney_xp_desc: "[GetTrait('tourney_participant').GetName( GetNullCharacter )] Experiente"
 reveler_xp_desc: "[GetTrait('lifestyle_reveler').GetName( GetNullCharacter )] Experiente"
 mystic_xp_desc: "Experiência como [GetTrait('lifestyle_mystic').GetName( GetNullCharacter )|l]"
 hunter_xp_desc: "[GetTrait('lifestyle_hunter').GetName( GetNullCharacter )] Experiente"
 blademaster_xp_desc: "[GetTrait('lifestyle_blademaster').GetName( GetNullCharacter )] Experiente"
 traveler_xp_desc: "[GetTrait('lifestyle_traveler').GetName( GetNullCharacter )] Experiente"
 physician_xp_desc: "[GetTrait('lifestyle_physician').GetName( GetNullCharacter )] Experiente"
 herbalist_xp_desc: "[GetTrait('lifestyle_herbalist').GetName( GetNullCharacter )] Experiente"
 loyal_interesting_desc: "É [GetTrait('loyal').GetName( GetNullCharacter )|l]"
 disloyal_interesting_desc: "É [GetTrait('disloyal').GetName( GetNullCharacter )|l]"
 faith_warrior_interesting_desc: "É [GetTrait('faith_warrior').GetName( GetNullCharacter )|l]"
 blood_of_prophet_interesting_desc: "Tem o [GetTrait('blood_of_prophet').GetName( GetNullCharacter )|l]"
 varangian_interesting_desc: "É [GetTrait('varangian').GetName( GetNullCharacter )|l]"
 poet_interesting_desc: "É [GetTrait('lifestyle_poet').GetName( GetNullCharacter )|l]"
 peasant_leader_interesting_desc: "É [GetTrait('peasant_leader').GetName( GetNullCharacter )|l]"
 populist_leader_interesting_desc: "É [GetTrait('populist_leader').GetName( GetNullCharacter )|l]"
 berserker_interesting_desc: "É [GetTrait('berserker').GetName( GetNullCharacter )|l]"
 born_in_the_purple_interesting_desc: "É [GetTrait('born_in_the_purple').GetName( GetNullCharacter )|l]"
 scaly_interesting_desc: "Tem Pele [GetTrait('scaly').GetName( GetNullCharacter )|l]"
 albino_interesting_desc: "É [GetTrait('albino').GetName( GetNullCharacter )|l]"
 dwarf_interesting_desc: "É [GetTrait('dwarf').GetName( GetNullCharacter )|l]"
 giant_interesting_desc: "É [GetTrait('giant').GetName( GetNullCharacter )|l]"
 devoted_interesting_desc: "É [GetTrait('devoted').GetName( GetNullCharacter )|l]"
 pure_blooded_interesting_desc: "É [GetTrait('pure_blooded').GetName( GetNullCharacter )|l]"
 crusader_king_interesting_desc: "É [GetTrait('crusader_king').GetName( GetNullCharacter )|l]"
 disinherited_interesting_desc: "É [GetTrait('disinherited').GetName( GetNullCharacter )|l]"
 blind_interesting_desc: "É [GetTrait('blind').GetName( GetNullCharacter )|l]"
 is_diarch_interesting_desc: "É um Diarca"
 ruler_in_foreign_lands_interesting_desc: "É um Governante em Terras Estrangeiras"
 valiant_knight_interesting_desc: "É um Cavaleiro Valoroso"
 sinful_bastard_interesting_desc: "É um [GetTrait('bastard').GetName( GetNullCharacter )|l] Pecador"
 adventurer_interesting_desc: "É um Aventureiro"
 liege_crusader_king_liege_lineage_interesting_desc: "Suserano da linhagem de [GetTrait('crusader_king').GetName( GetNullCharacter )|l]"
 holy_site_steward_interesting_desc: "A Capital é um Local Sagrado"
 has_a_legend_interesting_desc: "Tem uma Lenda"
 weak_hook_liege_interesting_desc: "Tem Gancho Fraco sobre o Suserano"
 strong_hook_liege_interesting_desc: "Tem Gancho Forte sobre o Suserano"
 beloved_by_pope_interesting_desc: "Querido pelo Papa"
 head_of_faith_interesting_desc: "É Chefe de Fé"
 stronger_than_liege_interesting_desc: "Mais Forte que o Suserano"
 small_king_interesting_desc: "É Governante de um Pequeno Reino"
 can_feudalize_interesting_desc: "Pode Feudalizar"
 multiduke_interesting_desc: "Possui muitos Ducados"
 legitimacy_interesting_desc: "Governante Extremamente Legítimo"
 non_dominant_gender_ambitious_char_interesting_desc: "É um Personagem Ambicioso de Gênero Não Dominante"
 non_dominant_gender_ruler_interesting_desc: "É um Governante de Gênero Não Dominante"
 treacherous_schemer_interesting_desc: "É um Maquinador Traiçoeiro"
 kind_hearted_diplomat_interesting_desc: "É um Diplomata Bondoso"
 different_faith_interesting_desc: "De Fé Diferente"
 greedy_steward_interesting_desc: "É um Administrador Ganancioso"
 brazen_commander_interesting_desc: "É um Comandante Ousado"
 pious_theologian_interesting_desc: "É um Teólogo Piedoso"
 salacious_seducer_interesting_desc: "É um Sedutor Devasso"
 high_skills_desc: "Habilidades Muito Altas"
 killed_a_lot_interesting_desc: "Matou Mais de 10 Pessoas"
 has_both_good_and_bad_genetics_desc: "Tem Traços Genéticos Bons e Ruins"
 good_genetics_desc: "Traços Genéticos Bons"
 bad_genetics_desc: "Traços Genéticos Ruins"
 holds_rome_interesting_desc: "Possui [GetTitleByKey('c_roma').GetBaseName]"
 holds_byzantion_interesting_desc: "Possui [GetTitleByKey('c_byzantion').GetBaseName]"
 holds_jerusalem_interesting_desc: "Possui [GetTitleByKey('c_jerusalem').GetBaseName]"
 holds_mecca_interesting_desc: "Possui [GetTitleByKey('c_mecca').GetBaseName]"
 holds_baghdad_interesting_desc: "Possui [GetTitleByKey('c_baghdad').GetBaseName]"
 holds_special_buildings_interesting_desc: "Controla Construções Especiais"
 has_historical_artifacts_interesting_desc: "Possui Artefatos Hist?ricos ?nicos"
 underrepresented_faith_interesting_desc: "É de uma Fé Sub-representada"
 underrepresented_culture_interesting_desc: "É de uma Cultura Sub-representada"
 outside_realm_desc: "Governante Independente"
 knows_many_secrets_interesting_desc: "Conhece Muitos Segredos"
 has_secrets_interesting_desc: "Tem Segredos"
 extremely_wealthy_interesting_desc: "Muito Rico"
 landless_heir_uninteresting_desc: "Herdeiro de Título Sem Terras"
 three_virtues_desc: "Tem Três Virtudes"
 three_sins_desc: "Tem Três Pecados"
 skills_difficulty: "Das Habilidades"
 legitimacy_difficulty: "Da Legitimidade"
 virtuous_traits_difficulty: "Tem Traços Virtuosos"
 physique_good_3_difficulty: "É [GetTrait('physique_good_3').GetName( GetNullCharacter )|l]"
 physique_good_2_difficulty: "É [GetTrait('physique_good_2').GetName( GetNullCharacter )|l]"
 physique_good_1_difficulty: "É [GetTrait('physique_good_1').GetName( GetNullCharacter )|l]"
 intellect_good_3_difficulty: "É [GetTrait('intellect_good_3').GetName( GetNullCharacter )|l]"
 intellect_good_2_difficulty: "É [GetTrait('intellect_good_2').GetName( GetNullCharacter )|l]"
 intellect_good_1_difficulty: "É [GetTrait('intellect_good_1').GetName( GetNullCharacter )|l]"
 beauty_good_3_difficulty: "É [GetTrait('beauty_good_3').GetName( GetNullCharacter )|l]"
 beauty_good_2_difficulty: "É [GetTrait('beauty_good_2').GetName( GetNullCharacter )|l]"
 beauty_good_1_difficulty: "É [GetTrait('beauty_good_1').GetName( GetNullCharacter )|l]"
 shrewd_difficulty: "É [GetTrait('shrewd').GetName( GetNullCharacter )|l]"
 strong_difficulty: "É [GetTrait('strong').GetName( GetNullCharacter )|l]"
 sinful_traits_difficulty: "Tem Traços Pecaminosos"
 incapable_difficulty: "É [GetTrait('incapable').GetName( GetNullCharacter )|l]"
 leper_difficulty: "É [GetTrait('leper').GetName( GetNullCharacter )|l]"
 maimed_difficulty: "É [GetTrait('maimed').GetName( GetNullCharacter )|l]"
 inbred_difficulty: "É [GetTrait('inbred').GetName( GetNullCharacter )|l]"
 severely_wounded_difficulty: "Está Gravemente Ferido"
 disinherited_difficulty: "É [GetTrait('disinherited').GetName( GetNullCharacter )|l]"
 sickly_difficulty: "É [GetTrait('sickly').GetName( GetNullCharacter )|l]"
 poxed_difficulty: "Tem [GetTrait('great_pox').GetName( GetNullCharacter )|l]"
 blind_difficulty: "É [GetTrait('blind').GetName( GetNullCharacter )|l]"
 infirm_difficulty: "É [GetTrait('infirm').GetName( GetNullCharacter )|l]"
 eunuch_difficulty: "É [GetTrait('eunuch_1').GetName( GetNullCharacter )|l]"
 lunatic_difficulty: "É [GetTrait('lunatic').GetName( GetNullCharacter )|l]"
 murderer_difficulty: "É [GetTrait('murderer').GetName( GetNullCharacter )|l]"
 excommunicated_difficulty: "Está Excomungado"
 bleeder_difficulty: "É [GetTrait('bleeder').GetName( GetNullCharacter )|l]"
 physique_bad_3_difficulty: "É [GetTrait('physique_bad_3').GetName( GetNullCharacter )|l]"
 physique_bad_2_difficulty: "É [GetTrait('physique_bad_2').GetName( GetNullCharacter )|l]"
 physique_bad_1_difficulty: "É [GetTrait('physique_bad_1').GetName( GetNullCharacter )|l]"
 intellect_bad_3_difficulty: "É [GetTrait('intellect_bad_3').GetName( GetNullCharacter )|l]"
 intellect_bad_2_difficulty: "É [GetTrait('intellect_bad_2').GetName( GetNullCharacter )|l]"
 intellect_bad_1_difficulty: "É [GetTrait('intellect_bad_1').GetName( GetNullCharacter )|l]"
 beauty_bad_3_difficulty: "É [GetTrait('beauty_bad_3').GetName( GetNullCharacter )|l]"
 beauty_bad_2_difficulty: "É [GetTrait('beauty_bad_2').GetName( GetNullCharacter )|l]"
 beauty_bad_1_difficulty: "É [GetTrait('beauty_bad_1').GetName( GetNullCharacter )|l]"
 dull_difficulty: "É [GetTrait('dull').GetName( GetNullCharacter )|l]"
 weak_difficulty: "É [GetTrait('weak').GetName( GetNullCharacter )|l]"
 sodomite_difficulty: "É [GetTrait('sodomite').GetName( GetNullCharacter )|l]"
 incestuous_difficulty: "É [GetTrait('incestuous').GetName( GetNullCharacter )|l]"
 fornicator_difficulty: "É [GetTrait('fornicator').GetName( GetNullCharacter )|l]"
 adulterer_difficulty: "É [GetTrait('adulterer').GetName( GetNullCharacter )|l]"
 cannibal_difficulty: "É [GetTrait('cannibal').GetName( GetNullCharacter )|l]"
 witch_difficulty: "É [GetTrait('witch').GetName( GetNullCharacter )|l]"
 kinslayer_difficulty: "É [GetTrait('kinslayer_1').GetName( GetNullCharacter )|l]"
 flagellant_difficulty: "É [GetTrait('flagellant').GetName( GetNullCharacter )|l]"
 improvident_difficulty: "É [GetTrait('improvident').GetName( GetNullCharacter )|l]"
 profligate_difficulty: "É [GetTrait('profligate').GetName( GetNullCharacter )|l]"
 disfigured_difficulty: "É [GetTrait('disfigured').GetName( GetNullCharacter )|l]"
 drunkard_difficulty: "É [GetTrait('drunkard').GetName( GetNullCharacter )|l]"
 possessed_difficulty: "É [GetTrait('possessed').GetName( GetNullCharacter )|l]"
 depressed_difficulty: "É [GetTrait('depressed').GetName( GetNullCharacter )|l]"
 infertile_difficulty: "É [GetTrait('infertile').GetName( GetNullCharacter )|l]"
 spindly_difficulty: "É [GetTrait('spindly').GetName( GetNullCharacter )|l]"
 paranoid_difficulty: "É [GetTrait('paranoid').GetName( GetNullCharacter )|l]"
 gout_difficulty: "Tem [GetTrait('gout_ridden').GetName( GetNullCharacter )|l]"
 wheezing_difficulty: "É [GetTrait('wheezing').GetName( GetNullCharacter )|l]"
 craven_difficulty: "É [GetTrait('craven').GetName( GetNullCharacter )|l]"
 shy_difficulty: "É [GetTrait('shy').GetName( GetNullCharacter )|l]"
 decadent_difficulty: "É [GetTrait('decadent').GetName( GetNullCharacter )|l]"
 denounced_difficulty: "É [GetTrait('denounced').GetName( GetNullCharacter )|l]"
 bastard_difficulty: "É [GetTrait('bastard').GetName( GetNullCharacter )|l]"
 weak_heritage_difficulty: "Tem Herança Fraca"
 comfort_eater_difficulty: "É [GetTrait('comfort_eater').GetName( GetNullCharacter )|l]"
 inappetetic_difficulty: "É [GetTrait('inappetetic').GetName( GetNullCharacter )|l]"
 reclusive_difficulty: "É [GetTrait('reclusive').GetName( GetNullCharacter )|l]"
 irritable_difficulty: "É [GetTrait('irritable').GetName( GetNullCharacter )|l]"
 rakish_difficulty: "É [GetTrait('rakish').GetName( GetNullCharacter )|l]"
 hashishiyah_difficulty: "É [GetTrait('hashishiyah').GetName( GetNullCharacter )|l]"
 celibate_difficulty: "É [GetTrait('celibate').GetName( GetNullCharacter )|l]"
 lovers_pox_difficulty: "Tem [GetTrait('lovers_pox').GetName( GetNullCharacter )|l]"
 wounded_difficulty: "É [GetTrait('wounded_1').GetName( GetNullCharacter )|l]"
 albino_difficulty: "É [GetTrait('albino').GetName( GetNullCharacter )|l]"
 lisping_difficulty: "Tem Impedimento [GetTrait('lisping').GetName( GetNullCharacter )|l]"
 stuttering_difficulty: "Tem Impedimento [GetTrait('stuttering').GetName( GetNullCharacter )|l]"
 giant_difficulty: "É [GetTrait('giant').GetName( GetNullCharacter )|l]"
 scaly_difficulty: "Tem Pele [GetTrait('scaly').GetName( GetNullCharacter )|l]"
 clubfooted_difficulty: "É [GetTrait('clubfooted').GetName( GetNullCharacter )|l]"
 dwarf_difficulty: "É [GetTrait('dwarf').GetName( GetNullCharacter )|l]"
 hunchbacked_difficulty: "É [GetTrait('hunchbacked').GetName( GetNullCharacter )|l]"
 lazy_difficulty: "É [GetTrait('lazy').GetName( GetNullCharacter )|l]"
 gluttonous_difficulty: "É [GetTrait('gluttonous').GetName( GetNullCharacter )|l]"
 deviant_difficulty: "É [GetTrait('deviant').GetName( GetNullCharacter )|l]"
 at_war_difficulty: "Em Guerra"
 losing_war_difficulty: "Perdendo Guerras"
 faction_difficulty: "Alvo de Facções Poderosas"
 powerful_neighbors_difficulty: "Governantes Vizinhos Poderosos"
 military_difficulty: "Força Militar"
 rivals_difficulty: "Tem Rivais"
 primary_heir_wrong_dynasty_difficulty: "Herdeiro Primário da Dinastia Errada"
 children_wrong_dynasty_difficulty: "Filhos são da Dinastia Errada"
 hostile_faith_liege_difficulty: "Suserano de Fé Hostil"
 nonpreferred_gender_difficulty: "Gênero Não Preferido na Fé"
 wrong_lineality_difficulty: "Linearidade Errada no Casamento"
 stress_level_difficulty: "Nível Alto de Stress"
 gold_difficulty: "Riqueza Excessiva"
 debt_level_difficulty: "Nível Alto de Dívida"
 is_ill_difficulty: "Sofrendo de Doença Debilitante"
 imprisoned_difficulty: "Preso"
 elder_difficulty: "Idade Avançada"
 poor_health_difficulty: "Saúde Ruim"
 is_a_vassal_difficulty: "É um Vassalo"
 non_adult_difficulty: "Criança"
 weak_domain_difficulty: "Domínio Fraco"
 unlanded_difficulty: "Não Possui Títulos"
 character_difficulty_text: "Dificuldade: [Character.Custom('CharacterDifficulty')|l]"
 character_difficulty_breakdown_header: "Detalhamento da Dificuldade"
 choose_destiny_header_text: "Escolha um Novo Destino"
 will_become_adventurer: "Se tornará um [GetGovernment('landless_adventurer_government').GetName|l]"
 character_interest_breakdown_header: "Aspectos Interessantes"
 different_government_desc: "Tem um Governo Diferente"
 opposite_struggle_faction_desc: "Facção Oposta em uma Luta"
